### ISSUE TITLE
Crash during removeBlindness event

### ISSUE THREAD

**Issue by Phweeeee** [Someone-Else-Was-Taken/BetterEndForge-Reforked#24] opened 2021-10-31 13:46 UTC
[debug.log](https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/files/7448941/debug.log)
[latest.log](https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/files/7448942/latest.log)

This occurs on BEFR 2.3.1.

**Comment by SSKirillSS** [comment] 2021-11-02 12:52
Duplicate of https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/issues/22

**Comment by KentaTheButcher** [comment] 2021-11-06 17:43
Is this bug getting solved?
Still happening in the last updates

**Closed** 2021-11-12 04:31 UTC
Labels: Resolved
