### ISSUE TITLE
crashloop

### ISSUE THREAD

**Issue by Reshirou** [Someone-Else-Was-Taken/BetterEndForge-Reforked#30] opened 2021-11-07 09:25 UTC
was pregenning world with Chunky and consistently ran into crashloops that bricked the worlds. Here is a crash report

https://pastebin.com/ScCyLwMK

already reported to Chunky Pregenerator, wasnt on their end

**Comment by SSKirillSS** [comment] 2021-11-08 13:29
Duplicate of https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/issues/20

You can disable umbra valley biome in the config to prevent crashing

**Closed** 2021-11-12 04:29 UTC
