### ISSUE TITLE
Blindness Resistance Crash

### ISSUE THREAD

**Issue by Reshy** [Someone-Else-Was-Taken/BetterEndForge-Reforked#31] opened 2021-11-08 06:06 UTC
Game randomly crashes looking for "Blindness Resistance".

[crash-2021-11-01_13.58.47-client.txt](https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/files/7494646/crash-2021-11-01_13.58.47-client.txt)

**Comment by Darkmega18** [comment] 2021-11-08 09:11
I just got this also. here is mine
[crash-2021-11-08_20.08.09-server.txt](https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/files/7495630/crash-2021-11-08_20.08.09-server.txt)
although mine seems to have come from server side instead.

**Comment by SSKirillSS** [comment] 2021-11-08 13:28
Duplicate of https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/issues/22

**Comment by Darkmega18** [comment] 2021-11-10 12:13
oh joy! now magnesium stops my loading if I use the old better end forge that wouldn't just decide to crash my game at random!

**Closed** 2021-11-11 07:16 UTC
Labels: Resolved
