### ISSUE TITLE
100% Constant Crash

### ISSUE THREAD

**Issue by SharkieTV** [Someone-Else-Was-Taken/BetterEndForge-Reforked#23] opened 2021-10-31 02:53 UTC
Crash https://pastebin.com/YdzJmNPu in the Better Minecraft Modpack, had to remove it, will add later when its more stable

**Comment by SSKirillSS** [comment] 2021-10-31 19:08
Duplicate of: https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/issues/20

**Closed** 2021-11-12 04:30 UTC
Labels: Resolved
